# Generated by Django 3.2.3 on 2021-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'default_related_name': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'default_related_name': 'movies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='core.Genre'),
        ),
    ]
